version: '3.3'
services:
  space-base-server:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: space_base_server
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:8080"